### ISSUE TITLE
S2 combinator

### ISSUE THREAD

**Issue by Moony7** [loophp/combinator#25]
Thanks for the great list!

I have a question regarding the S2 combinator. Is it the same as Curry's formalizing combinator Φ?
Because if it is, it should be λabcd.a(bd)(cd) instead of λabcd.a((bd)(cd)), like in the JS. I am asking because I have never seen the combinator λabcd.a((bd)(cd)) and would like to add it to my own list if it's a widely-used combinator.

Moony

**Comment by drupol** [comment]
Hello,

You're right, there's a discrepancy there. Are you willing to submit the PR to fix it?
